spring:
  application:
    name: "monitor-sample"

server:
  port: 6060
management:
  server:
    port: 6070
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    loggers:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true

logging:
  file:
    path: /opt/logs/
